// SPDX-License-Identifier: Apache-2.0
//! Device identity and enrollment key material.

use crate::transfer::SeenEnvelopeIds;
use crate::transfer::{
    create_envelope, open_envelope, CreateEnvelopeParams, OpenEnvelopeParams, SecretPayload,
    TransferEnvelope, TransferError, TrustedSender,
};
use meissnerseal_crypto::types::Key;
use meissnerseal_crypto::{
    aead::{self, Ciphertext},
    types::{AeadKey, XChaCha20Nonce},
};
use meissnerseal_pqc::{
    hybrid::{x25519_public_from_private, X25519PrivateKey, X25519PublicKey},
    mldsa::{self, SigningAlgorithmId, SigningPrivateKey, SigningPublicKey},
    mlkem::{MlKemPrivateKey, MlKemPublicKey},
};
use zeroize::Zeroizing;
use zeroize::{Zeroize, ZeroizeOnDrop};

/// Device identifier length in bytes.
pub const DEVICE_ID_LEN: usize = 16;

/// Domain-separation prefix for DEVICE-1 enrollment signatures.
pub const DEVICE_ENROLLMENT_SIGNING_DOMAIN: &[u8] = b"meissnerseal.device.enrollment.v1\x00";
const SEALED_DEVICE_KEY_FILE_MAGIC: &[u8; 6] = b"MSDKP\x01";
const SEALED_DEVICE_KEY_FILE_VERSION: u8 = 1;
const SEALED_DEVICE_KEY_FILE_AAD_DOMAIN: &[u8] = b"meissnerseal.device.keyfile.v1";

/// A 128-bit random device identifier.
pub type DeviceId = [u8; DEVICE_ID_LEN];

/// Unix timestamp in milliseconds.
pub type Timestamp = u64;

/// Device trust state for pairing, sync, and transfer policy.
///
/// # Contract
///
/// ## Preconditions
/// - Callers must validate state transitions before persisting or acting on
///   trust changes.
/// - `Verified` and `Approved` identities must carry a signing public key.
///
/// ## Postconditions
/// - Validation rejects `Verified` or `Approved` identities that have no
///   signing public key.
///
/// ## Invariants
/// - `Revoked` and `Expired` are terminal states for DEVICE-1 policy.
/// - Invalid transitions return `Err`; they are never silently accepted.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DeviceTrustState {
    Untrusted,
    PendingInbound,
    PendingOutbound,
    Verified,
    Approved,
    Revoked,
    Expired,
}

/// Public device identity advertised in pairing and transfer metadata.
///
/// # Contract
///
/// ## Preconditions
/// - `device_id` must be 128-bit random material generated by the core device
///   identity generator.
/// - `classical_public_key` must be the public half of an X25519 keypair from
///   `meissnerseal-pqc`.
/// - `pqc_public_key` must be the public half of an ML-KEM-768 keypair from
///   `meissnerseal-pqc`.
/// - `signing_public_key`, when present, must be algorithm-tagged per ADR-028.
///
/// ## Postconditions
/// - `validate()` returns `Err` for identities whose trust state requires a
///   signing key but whose `signing_public_key` is `None`.
///
/// ## Invariants
/// - The signing key type is `mldsa::SigningPublicKey`; the obsolete bare
///   Ed25519 type in `transfer_profile_v1.md §6` is superseded by ADR-028.
/// - Public key bytes never travel without their algorithm identifier.
#[derive(Debug)]
pub struct DeviceIdentity {
    pub device_id: DeviceId,
    pub display_name: String,
    pub classical_public_key: X25519PublicKey,
    pub pqc_public_key: MlKemPublicKey,
    pub signing_public_key: Option<SigningPublicKey>,
    pub created_at: Timestamp,
    pub trust_state: DeviceTrustState,
}

impl DeviceIdentity {
    /// Validate the structural invariants of a device identity.
    ///
    /// # Contract
    ///
    /// ## Preconditions
    /// - Identity fields must be fully populated before reaching sync or
    ///   transfer logic.
    ///
    /// ## Postconditions
    /// - Returns `Err(MissingSigningKey)` for `Verified` or `Approved`
    ///   identities without a signing public key.
    /// - Returns `Err(EmptyDisplayName)` when `display_name` is empty.
    ///
    /// ## Invariants
    /// - Validation is fail-closed and returns no partial trust decision.
    pub fn validate(&self) -> Result<()> {
        if self.display_name.is_empty() {
            return Err(DeviceIdentityError::EmptyDisplayName);
        }
        if matches!(
            self.trust_state,
            DeviceTrustState::Verified | DeviceTrustState::Approved
        ) && self.signing_public_key.is_none()
        {
            return Err(DeviceIdentityError::MissingSigningKey);
        }
        Ok(())
    }
}

/// Private key holder for a device identity.
///
/// # Contract
///
/// ## Preconditions
/// - Constructed only by `generate()` after all required keypairs have been
///   generated successfully.
/// - No partial `DeviceKeypair` is returned if any key generation step fails.
///
/// ## Postconditions
/// - Contains the X25519 private key, ML-KEM-768 private key, and Ed25519V1
///   signing private key matching a generated `DeviceIdentity`.
///
/// ## Invariants
/// - Implements `Zeroize` and `ZeroizeOnDrop`.
/// - `Debug` output is redacted and never includes key material.
/// - Does not implement `Clone`.
pub struct DeviceKeypair {
    classical_private_key: X25519PrivateKey,
    pqc_private_key: MlKemPrivateKey,
    signing_private_key: SigningPrivateKey,
}

impl DeviceKeypair {
    #[must_use]
    pub(crate) fn new(
        classical_private_key: X25519PrivateKey,
        pqc_private_key: MlKemPrivateKey,
        signing_private_key: SigningPrivateKey,
    ) -> Self {
        Self {
            classical_private_key,
            pqc_private_key,
            signing_private_key,
        }
    }
}

impl core::fmt::Debug for DeviceKeypair {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str("DeviceKeypair([REDACTED])")
    }
}

impl Zeroize for DeviceKeypair {
    fn zeroize(&mut self) {
        self.classical_private_key.zeroize();
        self.pqc_private_key.zeroize();
        self.signing_private_key.zeroize();
    }
}

impl ZeroizeOnDrop for DeviceKeypair {}

/// Sealed device keypair file API.
pub struct SealedDeviceKeyFile;

#[derive(Debug, thiserror::Error)]
pub enum DeviceIdentityError {
    #[error("device identity generation is not implemented")]
    Unimplemented,
    #[error("device identity file format is unknown or corrupt")]
    InvalidFileFormat,
    #[error("device display name must not be empty")]
    EmptyDisplayName,
    #[error("device identity requires a signing public key")]
    MissingSigningKey,
    #[error("invalid signing public key length")]
    InvalidSigningPublicKeyLength,
    #[error("device random bytes length mismatch")]
    RandomBytesLength,
    #[error("device key generation failed")]
    KeyGenerationFailed,
    #[error("device timestamp overflow")]
    TimestampOverflow,
    #[error("device signing operation failed")]
    SigningFailed,
    #[error("device keypair sealing failed")]
    SealingFailed,
    #[error("device keypair opening failed")]
    OpenFailed,
    #[error("device identity fingerprint mismatch")]
    IdentityFingerprintMismatch,
}

pub type Result<T> = core::result::Result<T, DeviceIdentityError>;

/// Generate a new public device identity and private key holder.
///
/// # Contract
///
/// ## Preconditions
/// - `display_name` must be non-empty.
/// - All cryptographic key generation must go through `meissnerseal-pqc`
///   abstractions; core must not call `ed25519-dalek`, `x25519-dalek`, or
///   ML-KEM backends directly.
///
/// ## Postconditions
/// - On success, returns a 16-byte random `device_id`, X25519 public key,
///   ML-KEM-768 public key, Ed25519V1 signing public key, creation timestamp,
///   and matching private `DeviceKeypair`.
/// - On any failure, returns `Err` and exposes no partial key material.
///
/// ## Invariants
/// - Generated signing material is tagged `SigningAlgorithmId::Ed25519V1`.
/// - No plaintext secret key material is logged, printed, or included in
///   errors.
pub fn generate(display_name: String) -> Result<(DeviceIdentity, DeviceKeypair)> {
    if display_name.is_empty() {
        return Err(DeviceIdentityError::EmptyDisplayName);
    }
    let id_bytes = meissnerseal_crypto::rng::random_bytes(DEVICE_ID_LEN);
    let device_id: DeviceId = id_bytes
        .try_into()
        .map_err(|_| DeviceIdentityError::RandomBytesLength)?;
    let (classical_private, classical_public) = meissnerseal_pqc::hybrid::x25519_keypair();
    let (pqc_public, pqc_private) =
        meissnerseal_pqc::mlkem::keypair().map_err(|_| DeviceIdentityError::KeyGenerationFailed)?;
    let (signing_public, signing_private) = meissnerseal_pqc::mldsa::ed25519_keypair();
    let created_at = unix_time_millis()?;

    let identity = DeviceIdentity {
        device_id,
        display_name,
        classical_public_key: classical_public,
        pqc_public_key: pqc_public,
        signing_public_key: Some(signing_public),
        created_at,
        trust_state: DeviceTrustState::Untrusted,
    };
    let keypair = DeviceKeypair::new(classical_private, pqc_private, signing_private);
    Ok((identity, keypair))
}

/// Construct a validated Ed25519V1 signing public key from fixed-length bytes.
///
/// # Contract
///
/// ## Preconditions
/// - `bytes` must be exactly the 32-byte Ed25519 public key encoding.
///
/// ## Postconditions
/// - Returns a `SigningPublicKey` tagged `SigningAlgorithmId::Ed25519V1`.
///
/// ## Invariants
/// - Callers cannot accidentally construct a wrong-length Ed25519 key through
///   this typed constructor.
pub fn try_new_ed25519_signing_public_key(bytes: [u8; 32]) -> Result<SigningPublicKey> {
    Ok(SigningPublicKey::new(
        SigningAlgorithmId::Ed25519V1,
        bytes.to_vec(),
    ))
}

/// Construct a validated signing public key from byte slices.
///
/// # Contract
///
/// ## Preconditions
/// - `algorithm` determines the exact expected byte length.
///
/// ## Postconditions
/// - Ed25519V1 accepts exactly 32 bytes and rejects all other lengths.
/// - The hybrid slot fails closed until the future PQ signing backend is
///   implemented.
///
/// ## Invariants
/// - Accepts variable-length byte slices so callers that receive wire bytes
///   do not need to promote them into fixed-length arrays before validation.
pub fn try_new_signing_public_key(
    algorithm: SigningAlgorithmId,
    bytes: &[u8],
) -> Result<SigningPublicKey> {
    match algorithm {
        SigningAlgorithmId::Ed25519V1 => {
            let key_bytes: [u8; 32] = bytes
                .try_into()
                .map_err(|_| DeviceIdentityError::InvalidSigningPublicKeyLength)?;
            try_new_ed25519_signing_public_key(key_bytes)
        }
        SigningAlgorithmId::Ed25519MlDsa87HybridV1 => Err(DeviceIdentityError::Unimplemented),
    }
}

/// Build the domain-separated enrollment transcript bytes for signing.
///
/// # Contract
///
/// ## Preconditions
/// - `message` is the device-enrollment payload to authenticate.
///
/// ## Postconditions
/// - Returns `DEVICE_ENROLLMENT_SIGNING_DOMAIN || message`.
///
/// ## Invariants
/// - All bytes passed from DEVICE-1 to `mldsa::sign()` must be produced by
///   this helper or by an equivalent construction with the same prefix.
pub fn enrollment_signing_message(message: &[u8]) -> Vec<u8> {
    let mut signed = Vec::new();
    signed.extend_from_slice(DEVICE_ENROLLMENT_SIGNING_DOMAIN);
    signed.extend_from_slice(message);
    signed
}

/// Sign a device-enrollment payload with the DEVICE-1 domain prefix.
///
/// # Contract
///
/// ## Preconditions
/// - `private_key` must be an algorithm-tagged signing key from the generated
///   device keypair.
/// - `message` must be the raw device-enrollment payload, not already signed
///   content.
///
/// ## Postconditions
/// - Calls `mldsa::sign()` with
///   `b"meissnerseal.device.enrollment.v1\x00" || message`.
/// - Returns `Err` if the PQC signing boundary rejects the operation.
///
/// ## Invariants
/// - Core owns the domain-separation prefix; `meissnerseal-pqc` does not add
///   it implicitly.
pub fn sign_enrollment_message(
    private_key: &SigningPrivateKey,
    message: &[u8],
) -> Result<mldsa::Signature> {
    mldsa::sign_with_domain(private_key, DEVICE_ENROLLMENT_SIGNING_DOMAIN, message)
        .map_err(|_| DeviceIdentityError::SigningFailed)
}

/// Serialize raw keypair bytes for the current unsecured developer format.
///
/// # Contract
///
/// ## Preconditions
/// - `identity` and `keypair` must refer to the same device.
/// - Callers must treat the returned bytes as secret plaintext key material.
///
/// ## Postconditions
/// - Returns version-tagged raw keypair bytes used internally by
///   `SealedDeviceKeyFile::seal` as the AEAD plaintext.
///
/// ## Invariants
/// - The returned bytes are secret-bearing and must not be logged, printed, or
///   exposed through public file APIs.
pub(crate) fn serialize_keypair_bytes(
    identity: &DeviceIdentity,
    keypair: &DeviceKeypair,
) -> Zeroizing<Vec<u8>> {
    let mut out = Zeroizing::new(Vec::new());
    out.push(1);
    out.extend_from_slice(&identity.device_id);
    out.extend_from_slice(identity.classical_public_key.as_slice());
    out.extend_from_slice(keypair.classical_private_key.as_slice());
    out.extend_from_slice(keypair.pqc_private_key.as_slice());
    out.extend_from_slice(&keypair.signing_private_key.algorithm().to_le_bytes());
    keypair.signing_private_key.with_secret_bytes(|secret| {
        let len = u32::try_from(secret.len()).unwrap_or(u32::MAX);
        out.extend_from_slice(&len.to_le_bytes());
        out.extend_from_slice(secret);
    });
    out
}

/// Deserialize the current raw developer keypair byte format.
///
/// # Contract
///
/// ## Preconditions
/// - `bytes` must be the exact raw developer format emitted by
///   `serialize_keypair_bytes`.
///
/// ## Postconditions
/// - Returns the parsed keypair only when the framing is valid and the
///   recomputed X25519 public key matches the encoded public key bytes.
/// - Used internally by `SealedDeviceKeyFile::open` after AEAD decryption.
///
/// ## Invariants
/// - Fail closed on malformed framing or mismatched public/private key
///   material.
pub(crate) fn deserialize_keypair_bytes(
    bytes: &[u8],
) -> Result<(DeviceId, X25519PublicKey, DeviceKeypair)> {
    let mut parser = ByteParser::new(bytes);
    if parser.take_u8()? != 1 {
        return Err(DeviceIdentityError::InvalidFileFormat);
    }
    let device_id: DeviceId = parser.take_array()?;
    let classical_public_key = X25519PublicKey::from_bytes(parser.take_array()?);
    let classical_private_key = X25519PrivateKey::from_bytes(parser.take_array()?);
    let pqc_private_key = MlKemPrivateKey::from_bytes(parser.take_array()?);
    let signing_algorithm = SigningAlgorithmId::from_u16(parser.take_u16_le()?)
        .map_err(|_| DeviceIdentityError::InvalidFileFormat)?;
    let signing_len = parser.take_u32_le()? as usize;
    if signing_algorithm == SigningAlgorithmId::Ed25519V1 && signing_len != 32 {
        return Err(DeviceIdentityError::InvalidFileFormat);
    }
    let signing_private_key =
        SigningPrivateKey::new(signing_algorithm, parser.take_vec(signing_len)?);
    if !parser.is_empty() {
        return Err(DeviceIdentityError::InvalidFileFormat);
    }
    let recomputed_classical_public_key = x25519_public_from_private(&classical_private_key);
    if !bool::from(classical_public_key.ct_eq(&recomputed_classical_public_key)) {
        return Err(DeviceIdentityError::InvalidFileFormat);
    }
    Ok((
        device_id,
        classical_public_key,
        DeviceKeypair::new(classical_private_key, pqc_private_key, signing_private_key),
    ))
}

impl SealedDeviceKeyFile {
    pub fn seal(
        identity: &DeviceIdentity,
        keypair: &DeviceKeypair,
        dkek: &AeadKey,
    ) -> Result<Zeroizing<Vec<u8>>> {
        let raw_keypair = serialize_keypair_bytes(identity, keypair);
        let identity_bytes = serialize_identity_bytes(identity)?;
        let fingerprint = identity_fingerprint(identity);
        let aad = sealed_device_key_file_aad(identity_bytes.as_slice(), &fingerprint)?;
        let (ciphertext, nonce) = aead::encrypt(dkek, raw_keypair.as_slice(), &aad)
            .map_err(|_| DeviceIdentityError::SealingFailed)?;
        serialize_sealed_device_key_file(
            identity_bytes.as_slice(),
            &fingerprint,
            &nonce,
            ciphertext.as_ref(),
        )
    }

    pub fn open(bytes: &[u8], dkek: &AeadKey) -> Result<(DeviceIdentity, DeviceKeypair)> {
        let parsed = parse_sealed_device_key_file(bytes)?;
        let aad = sealed_device_key_file_aad(parsed.identity_bytes, &parsed.fingerprint)?;
        let nonce = XChaCha20Nonce::from_bytes(parsed.nonce);
        let ciphertext = Ciphertext::from(parsed.ciphertext.to_vec());
        let plaintext = aead::decrypt(dkek, &nonce, &ciphertext, &aad)
            .map_err(|_| DeviceIdentityError::OpenFailed)?;
        let identity = deserialize_identity_bytes(parsed.identity_bytes)?;
        let (device_id, classical_public_key, keypair) =
            deserialize_keypair_bytes(plaintext.as_ref())?;
        if identity.device_id != device_id
            || !bool::from(identity.classical_public_key.ct_eq(&classical_public_key))
        {
            return Err(DeviceIdentityError::IdentityFingerprintMismatch);
        }
        let derived_identity = rebuild_identity_from_keypair(&identity, &keypair)?;
        let recomputed_fingerprint = identity_fingerprint(&derived_identity);
        if parsed.fingerprint != recomputed_fingerprint {
            return Err(DeviceIdentityError::IdentityFingerprintMismatch);
        }
        Ok((derived_identity, keypair))
    }
}

pub fn serialize_identity_text(identity: &DeviceIdentity) -> String {
    let signing_public_key = identity
        .signing_public_key
        .as_ref()
        .map(SigningPublicKey::as_bytes)
        .unwrap_or(&[]);
    let mut out = String::new();
    out.push_str("ms-device-identity-v1\n");
    out.push_str("device_id=");
    out.push_str(&hex_encode(&identity.device_id));
    out.push('\n');
    out.push_str("display_name=");
    out.push_str(&identity.display_name);
    out.push('\n');
    out.push_str("classical_public_key=");
    out.push_str(&hex_encode(identity.classical_public_key.as_slice()));
    out.push('\n');
    out.push_str("pqc_public_key=");
    out.push_str(&hex_encode(identity.pqc_public_key.as_slice()));
    out.push('\n');
    out.push_str("signing_algorithm=Ed25519V1\n");
    out.push_str("signing_public_key=");
    out.push_str(&hex_encode(signing_public_key));
    out.push('\n');
    out.push_str("created_at=");
    out.push_str(&identity.created_at.to_string());
    out.push('\n');
    out
}

pub fn deserialize_identity_text(text: &str) -> Result<DeviceIdentity> {
    let mut lines = text.lines();
    if lines.next() != Some("ms-device-identity-v1") {
        return Err(DeviceIdentityError::InvalidFileFormat);
    }
    let mut device_id = None;
    let mut display_name = None;
    let mut classical_public_key = None;
    let mut pqc_public_key = None;
    let mut signing_algorithm = None;
    let mut signing_public_key = None;
    let mut created_at = None;

    for line in lines {
        let (key, value) = line
            .split_once('=')
            .ok_or(DeviceIdentityError::InvalidFileFormat)?;
        match key {
            "device_id" => device_id = Some(hex_array::<16>(value)?),
            "display_name" if !value.contains('\n') => display_name = Some(value.to_owned()),
            "classical_public_key" => {
                classical_public_key = Some(Key::from_bytes(hex_array::<32>(value)?));
            }
            "pqc_public_key" => {
                pqc_public_key = Some(Key::from_bytes(hex_array::<1184>(value)?));
            }
            "signing_algorithm" if value == "Ed25519V1" => {
                signing_algorithm = Some(SigningAlgorithmId::Ed25519V1);
            }
            "signing_public_key" => signing_public_key = Some(hex_decode(value)?),
            "created_at" => {
                created_at = Some(
                    value
                        .parse::<Timestamp>()
                        .map_err(|_| DeviceIdentityError::InvalidFileFormat)?,
                );
            }
            _ => return Err(DeviceIdentityError::InvalidFileFormat),
        }
    }

    let signing_public_key = try_new_signing_public_key(
        signing_algorithm.ok_or(DeviceIdentityError::InvalidFileFormat)?,
        &signing_public_key.ok_or(DeviceIdentityError::InvalidFileFormat)?,
    )?;
    let identity = DeviceIdentity {
        device_id: device_id.ok_or(DeviceIdentityError::InvalidFileFormat)?,
        display_name: display_name.ok_or(DeviceIdentityError::InvalidFileFormat)?,
        classical_public_key: classical_public_key.ok_or(DeviceIdentityError::InvalidFileFormat)?,
        pqc_public_key: pqc_public_key.ok_or(DeviceIdentityError::InvalidFileFormat)?,
        signing_public_key: Some(signing_public_key),
        created_at: created_at.ok_or(DeviceIdentityError::InvalidFileFormat)?,
        trust_state: DeviceTrustState::Untrusted,
    };
    identity.validate()?;
    Ok(identity)
}

pub fn create_signed_transfer_envelope(
    sender_device_id: DeviceId,
    sender_keypair: &DeviceKeypair,
    recipient_device_id: Option<DeviceId>,
    recipient_classical_public_key: X25519PublicKey,
    recipient_pqc_public_key: MlKemPublicKey,
    plaintext: SecretPayload,
    expires_at: Option<Timestamp>,
) -> core::result::Result<TransferEnvelope, TransferError> {
    let signing_algorithm = sender_keypair.signing_private_key.algorithm();
    let sender_signing_private_key = sender_keypair
        .signing_private_key
        .with_secret_bytes(|bytes| SigningPrivateKey::new(signing_algorithm, bytes.to_vec()));
    create_envelope(CreateEnvelopeParams {
        sender_device_id,
        recipient_device_id,
        anonymous_recipient_public_key: recipient_device_id
            .is_none()
            .then_some(recipient_classical_public_key.clone()),
        recipient_classical_public_key,
        recipient_pqc_public_key,
        sender_signing_private_key,
        plaintext_payload: plaintext,
        expires_at,
    })
}

pub fn open_received_transfer_envelope(
    envelope: &TransferEnvelope,
    recipient_keypair: &DeviceKeypair,
    recipient_classical_public_key: X25519PublicKey,
    sender_signing_public_key: TrustedSender,
    seen: &mut SeenEnvelopeIds,
) -> core::result::Result<SecretPayload, TransferError> {
    open_envelope(
        envelope,
        OpenEnvelopeParams {
            recipient_classical_private_key: X25519PrivateKey::from_bytes(
                *recipient_keypair.classical_private_key.as_bytes(),
            ),
            recipient_classical_public_key,
            recipient_pqc_private_key: MlKemPrivateKey::from_bytes(
                *recipient_keypair.pqc_private_key.as_bytes(),
            ),
            sender_signing_public_key,
        },
        seen,
    )
}

fn serialize_identity_bytes(identity: &DeviceIdentity) -> Result<Zeroizing<Vec<u8>>> {
    let mut out = Zeroizing::new(Vec::new());
    out.push(1);
    out.extend_from_slice(&identity.device_id);
    out.extend_from_slice(
        &u32::try_from(identity.display_name.len())
            .map_err(|_| DeviceIdentityError::InvalidFileFormat)?
            .to_le_bytes(),
    );
    out.extend_from_slice(identity.display_name.as_bytes());
    out.extend_from_slice(identity.classical_public_key.as_slice());
    out.extend_from_slice(identity.pqc_public_key.as_slice());
    match identity.signing_public_key.as_ref() {
        Some(signing_public_key) => {
            out.push(1);
            out.extend_from_slice(&signing_public_key.algorithm().to_le_bytes());
            out.extend_from_slice(
                &u32::try_from(signing_public_key.as_bytes().len())
                    .map_err(|_| DeviceIdentityError::InvalidFileFormat)?
                    .to_le_bytes(),
            );
            out.extend_from_slice(signing_public_key.as_bytes());
        }
        None => out.push(0),
    }
    out.extend_from_slice(&identity.created_at.to_le_bytes());
    out.push(device_trust_state_to_u8(identity.trust_state));
    Ok(out)
}

fn deserialize_identity_bytes(bytes: &[u8]) -> Result<DeviceIdentity> {
    let mut parser = ByteParser::new(bytes);
    if parser.take_u8()? != 1 {
        return Err(DeviceIdentityError::InvalidFileFormat);
    }
    let device_id = parser.take_array()?;
    let display_name_len = parser.take_u32_le()? as usize;
    let display_name = std::str::from_utf8(parser.take(display_name_len)?)
        .map_err(|_| DeviceIdentityError::InvalidFileFormat)?
        .to_owned();
    let classical_public_key = X25519PublicKey::from_bytes(parser.take_array()?);
    let pqc_public_key = MlKemPublicKey::from_bytes(parser.take_array()?);
    let signing_public_key = match parser.take_u8()? {
        0 => None,
        1 => {
            let algorithm = SigningAlgorithmId::from_u16(parser.take_u16_le()?)
                .map_err(|_| DeviceIdentityError::InvalidFileFormat)?;
            let len = parser.take_u32_le()? as usize;
            Some(try_new_signing_public_key(algorithm, parser.take(len)?)?)
        }
        _ => return Err(DeviceIdentityError::InvalidFileFormat),
    };
    let created_at = parser.take_u64_le()?;
    let trust_state = device_trust_state_from_u8(parser.take_u8()?)?;
    if !parser.is_empty() {
        return Err(DeviceIdentityError::InvalidFileFormat);
    }
    let identity = DeviceIdentity {
        device_id,
        display_name,
        classical_public_key,
        pqc_public_key,
        signing_public_key,
        created_at,
        trust_state,
    };
    identity.validate()?;
    Ok(identity)
}

fn identity_fingerprint(identity: &DeviceIdentity) -> [u8; 32] {
    let mut canonical = Vec::new();
    canonical.extend_from_slice(&identity.device_id);
    canonical.extend_from_slice(
        &u32::try_from(identity.display_name.len())
            .unwrap_or(u32::MAX)
            .to_le_bytes(),
    );
    canonical.extend_from_slice(identity.display_name.as_bytes());
    canonical.extend_from_slice(identity.classical_public_key.as_slice());
    canonical.extend_from_slice(identity.pqc_public_key.as_slice());
    match identity.signing_public_key.as_ref() {
        Some(signing_public_key) => {
            canonical.push(1);
            canonical.extend_from_slice(&signing_public_key.algorithm().to_le_bytes());
            canonical.extend_from_slice(
                &u32::try_from(signing_public_key.as_bytes().len())
                    .unwrap_or(u32::MAX)
                    .to_le_bytes(),
            );
            canonical.extend_from_slice(signing_public_key.as_bytes());
        }
        None => canonical.push(0),
    }
    canonical.extend_from_slice(&identity.created_at.to_le_bytes());
    canonical.push(match identity.trust_state {
        DeviceTrustState::Untrusted => 0,
        DeviceTrustState::PendingInbound => 1,
        DeviceTrustState::PendingOutbound => 2,
        DeviceTrustState::Verified => 3,
        DeviceTrustState::Approved => 4,
        DeviceTrustState::Revoked => 5,
        DeviceTrustState::Expired => 6,
    });
    meissnerseal_crypto::hash::blake2b_256_bytes(&canonical)
}

fn rebuild_identity_from_keypair(
    identity: &DeviceIdentity,
    keypair: &DeviceKeypair,
) -> Result<DeviceIdentity> {
    let classical_public_key = x25519_public_from_private(&keypair.classical_private_key);
    let signing_public_key = identity
        .signing_public_key
        .clone()
        .ok_or(DeviceIdentityError::MissingSigningKey)?;
    validate_signing_key_matches_public(&keypair.signing_private_key, &signing_public_key)?;
    Ok(DeviceIdentity {
        device_id: identity.device_id,
        display_name: identity.display_name.clone(),
        classical_public_key,
        pqc_public_key: identity.pqc_public_key.clone(),
        signing_public_key: Some(signing_public_key),
        created_at: identity.created_at,
        trust_state: identity.trust_state,
    })
}

fn validate_signing_key_matches_public(
    private_key: &SigningPrivateKey,
    public_key: &SigningPublicKey,
) -> Result<()> {
    const MESSAGE: &[u8] = b"meissnerseal.device.keyfile.check.v1";
    let signature = mldsa::sign_with_domain(private_key, DEVICE_ENROLLMENT_SIGNING_DOMAIN, MESSAGE)
        .map_err(|_| DeviceIdentityError::IdentityFingerprintMismatch)?;
    mldsa::verify_with_domain(
        public_key,
        DEVICE_ENROLLMENT_SIGNING_DOMAIN,
        MESSAGE,
        &signature,
    )
    .map_err(|_| DeviceIdentityError::IdentityFingerprintMismatch)
}

fn device_trust_state_to_u8(state: DeviceTrustState) -> u8 {
    match state {
        DeviceTrustState::Untrusted => 0,
        DeviceTrustState::PendingInbound => 1,
        DeviceTrustState::PendingOutbound => 2,
        DeviceTrustState::Verified => 3,
        DeviceTrustState::Approved => 4,
        DeviceTrustState::Revoked => 5,
        DeviceTrustState::Expired => 6,
    }
}

fn device_trust_state_from_u8(value: u8) -> Result<DeviceTrustState> {
    match value {
        0 => Ok(DeviceTrustState::Untrusted),
        1 => Ok(DeviceTrustState::PendingInbound),
        2 => Ok(DeviceTrustState::PendingOutbound),
        3 => Ok(DeviceTrustState::Verified),
        4 => Ok(DeviceTrustState::Approved),
        5 => Ok(DeviceTrustState::Revoked),
        6 => Ok(DeviceTrustState::Expired),
        _ => Err(DeviceIdentityError::InvalidFileFormat),
    }
}

fn sealed_device_key_file_aad(identity_bytes: &[u8], fingerprint: &[u8; 32]) -> Result<Vec<u8>> {
    let mut aad = Vec::new();
    aad.extend_from_slice(SEALED_DEVICE_KEY_FILE_AAD_DOMAIN);
    aad.extend_from_slice(
        &u32::try_from(identity_bytes.len())
            .map_err(|_| DeviceIdentityError::InvalidFileFormat)?
            .to_le_bytes(),
    );
    aad.extend_from_slice(identity_bytes);
    aad.extend_from_slice(fingerprint);
    Ok(aad)
}

fn serialize_sealed_device_key_file(
    identity_bytes: &[u8],
    fingerprint: &[u8; 32],
    nonce: &XChaCha20Nonce,
    ciphertext: &[u8],
) -> Result<Zeroizing<Vec<u8>>> {
    let mut out = Zeroizing::new(Vec::new());
    out.extend_from_slice(SEALED_DEVICE_KEY_FILE_MAGIC);
    out.push(SEALED_DEVICE_KEY_FILE_VERSION);
    out.extend_from_slice(
        &u32::try_from(identity_bytes.len())
            .map_err(|_| DeviceIdentityError::InvalidFileFormat)?
            .to_le_bytes(),
    );
    out.extend_from_slice(identity_bytes);
    out.extend_from_slice(fingerprint);
    out.extend_from_slice(nonce.as_slice());
    out.extend_from_slice(
        &u32::try_from(ciphertext.len())
            .map_err(|_| DeviceIdentityError::InvalidFileFormat)?
            .to_le_bytes(),
    );
    out.extend_from_slice(ciphertext);
    Ok(out)
}

struct ParsedSealedDeviceKeyFile<'a> {
    identity_bytes: &'a [u8],
    fingerprint: [u8; 32],
    nonce: [u8; 24],
    ciphertext: &'a [u8],
}

fn parse_sealed_device_key_file(bytes: &[u8]) -> Result<ParsedSealedDeviceKeyFile<'_>> {
    let mut parser = ByteParser::new(bytes);
    if parser.take(SEALED_DEVICE_KEY_FILE_MAGIC.len())? != SEALED_DEVICE_KEY_FILE_MAGIC {
        return Err(DeviceIdentityError::InvalidFileFormat);
    }
    if parser.take_u8()? != SEALED_DEVICE_KEY_FILE_VERSION {
        return Err(DeviceIdentityError::InvalidFileFormat);
    }
    let identity_len = parser.take_u32_le()? as usize;
    let identity_bytes = parser.take(identity_len)?;
    let fingerprint = parser.take_array()?;
    let nonce = parser.take_array()?;
    let ciphertext_len = parser.take_u32_le()? as usize;
    let ciphertext = parser.take(ciphertext_len)?;
    if !parser.is_empty() {
        return Err(DeviceIdentityError::InvalidFileFormat);
    }
    Ok(ParsedSealedDeviceKeyFile {
        identity_bytes,
        fingerprint,
        nonce,
        ciphertext,
    })
}

fn hex_encode(bytes: &[u8]) -> String {
    let mut out = String::new();
    for byte in bytes {
        let _ = std::fmt::Write::write_fmt(&mut out, format_args!("{byte:02x}"));
    }
    out
}

fn hex_decode(value: &str) -> Result<Vec<u8>> {
    if !value.len().is_multiple_of(2) {
        return Err(DeviceIdentityError::InvalidFileFormat);
    }
    let mut out = Vec::new();
    for pair in value.as_bytes().chunks(2) {
        let hex = std::str::from_utf8(pair).map_err(|_| DeviceIdentityError::InvalidFileFormat)?;
        out.push(u8::from_str_radix(hex, 16).map_err(|_| DeviceIdentityError::InvalidFileFormat)?);
    }
    Ok(out)
}

fn hex_array<const N: usize>(value: &str) -> Result<[u8; N]> {
    hex_decode(value)?
        .try_into()
        .map_err(|_| DeviceIdentityError::InvalidFileFormat)
}

struct ByteParser<'a> {
    bytes: &'a [u8],
    offset: usize,
}

impl<'a> ByteParser<'a> {
    fn new(bytes: &'a [u8]) -> Self {
        Self { bytes, offset: 0 }
    }

    fn is_empty(&self) -> bool {
        self.offset == self.bytes.len()
    }

    fn take(&mut self, len: usize) -> Result<&'a [u8]> {
        let end = self
            .offset
            .checked_add(len)
            .ok_or(DeviceIdentityError::InvalidFileFormat)?;
        let slice = self
            .bytes
            .get(self.offset..end)
            .ok_or(DeviceIdentityError::InvalidFileFormat)?;
        self.offset = end;
        Ok(slice)
    }

    fn take_u8(&mut self) -> Result<u8> {
        Ok(*self
            .take(1)?
            .first()
            .ok_or(DeviceIdentityError::InvalidFileFormat)?)
    }

    fn take_u16_le(&mut self) -> Result<u16> {
        Ok(u16::from_le_bytes(self.take_array()?))
    }

    fn take_u32_le(&mut self) -> Result<u32> {
        Ok(u32::from_le_bytes(self.take_array()?))
    }

    fn take_u64_le(&mut self) -> Result<u64> {
        Ok(u64::from_le_bytes(self.take_array()?))
    }

    fn take_array<const N: usize>(&mut self) -> Result<[u8; N]> {
        self.take(N)?
            .try_into()
            .map_err(|_| DeviceIdentityError::InvalidFileFormat)
    }

    fn take_vec(&mut self, len: usize) -> Result<Vec<u8>> {
        Ok(self.take(len)?.to_vec())
    }
}

fn unix_time_millis() -> Result<Timestamp> {
    let millis = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis();
    Timestamp::try_from(millis).map_err(|_| DeviceIdentityError::TimestampOverflow)
}

#[cfg(test)]
#[allow(clippy::expect_used)]
mod tests {
    use super::*;
    use crate::transfer::{TransferError, TrustedSender};
    use meissnerseal_crypto::types::Key;
    use static_assertions::assert_not_impl_any;

    assert_not_impl_any!(DeviceKeypair: Clone);

    const TEST_MESSAGE: &[u8] = b"device enrollment payload";

    #[test]
    fn generate_returns_device_identity_with_128_bit_device_id() {
        let (identity, _keypair) = generate("phase1-device".to_owned()).expect("generate succeeds");

        assert_eq!(identity.device_id.len(), DEVICE_ID_LEN);
    }

    #[test]
    fn generate_produces_ed25519_v1_signing_public_key() {
        let (identity, _keypair) = generate("phase1-device".to_owned()).expect("generate succeeds");
        let signing_public_key = identity
            .signing_public_key
            .as_ref()
            .expect("generated identity has signing key");

        assert_eq!(
            signing_public_key.algorithm(),
            SigningAlgorithmId::Ed25519V1
        );
    }

    #[test]
    fn enrollment_signing_message_prepends_domain_prefix() {
        let signed = enrollment_signing_message(TEST_MESSAGE);

        assert!(signed.starts_with(DEVICE_ENROLLMENT_SIGNING_DOMAIN));
        assert!(signed.ends_with(TEST_MESSAGE));
        assert_ne!(signed.as_slice(), TEST_MESSAGE);
    }

    #[test]
    fn prefixed_and_unprefixed_messages_produce_different_signatures() {
        let private_key = SigningPrivateKey::new(SigningAlgorithmId::Ed25519V1, vec![0x11; 32]);
        let raw_signature = mldsa::sign(&private_key, TEST_MESSAGE).expect("raw sign succeeds");
        let signed_message = enrollment_signing_message(TEST_MESSAGE);
        let prefixed_signature =
            mldsa::sign(&private_key, &signed_message).expect("prefixed sign succeeds");

        assert_ne!(raw_signature.as_bytes(), prefixed_signature.as_bytes());
    }

    #[test]
    fn try_new_ed25519_signing_public_key_rejects_wrong_length_input() {
        let wrong_length = [0u8; 31];

        assert!(matches!(
            try_new_signing_public_key(SigningAlgorithmId::Ed25519V1, &wrong_length),
            Err(DeviceIdentityError::InvalidSigningPublicKeyLength)
        ));
    }

    #[test]
    fn verified_or_approved_identity_without_signing_key_fails_validation() {
        let verified = identity_with_state(DeviceTrustState::Verified, None);
        let approved = identity_with_state(DeviceTrustState::Approved, None);

        assert!(matches!(
            verified.validate(),
            Err(DeviceIdentityError::MissingSigningKey)
        ));
        assert!(matches!(
            approved.validate(),
            Err(DeviceIdentityError::MissingSigningKey)
        ));
    }

    #[test]
    fn device_keypair_debug_is_redacted() {
        let keypair = DeviceKeypair::new(
            Key::from_bytes([0xA1; 32]),
            Key::from_bytes([0xB2; 2400]),
            SigningPrivateKey::new(SigningAlgorithmId::Ed25519V1, vec![0xC3; 32]),
        );
        let debug = format!("{keypair:?}");

        assert_eq!(debug, "DeviceKeypair([REDACTED])");
        assert!(!debug.contains("A1"));
        assert!(!debug.contains("B2"));
        assert!(!debug.contains("C3"));
    }

    #[test]
    fn generate_with_empty_display_name_returns_err() {
        assert!(matches!(
            generate(String::new()),
            Err(DeviceIdentityError::EmptyDisplayName)
        ));
    }

    #[test]
    fn deserialize_keypair_bytes_rejects_wrong_length_ed25519_private_key() {
        let (identity, keypair) = generate("phase1-device".to_owned()).expect("generate fixture");
        let mut serialized = serialize_keypair_bytes(&identity, &keypair).to_vec();
        let len_offset = 1 + DEVICE_ID_LEN + 32 + 32 + 2400 + 2;
        serialized
            .get_mut(len_offset..len_offset + 4)
            .expect("signing length field")
            .copy_from_slice(&31u32.to_le_bytes());
        serialized.truncate(len_offset + 4 + 31);

        assert!(matches!(
            deserialize_keypair_bytes(&serialized),
            Err(DeviceIdentityError::InvalidFileFormat)
        ));
    }

    #[test]
    fn deserialize_keypair_bytes_rejects_mismatched_x25519_public_key() {
        let (identity, keypair) = generate("phase1-device".to_owned()).expect("generate fixture");
        let mut serialized = serialize_keypair_bytes(&identity, &keypair).to_vec();
        *serialized
            .get_mut(1 + DEVICE_ID_LEN)
            .expect("classical public key byte") ^= 0x01;

        assert!(matches!(
            deserialize_keypair_bytes(&serialized),
            Err(DeviceIdentityError::InvalidFileFormat)
        ));
    }

    #[test]
    fn deserialize_keypair_bytes_rejects_trailing_garbage() {
        let (identity, keypair) = generate("phase1-device".to_owned()).expect("generate fixture");
        let mut serialized = serialize_keypair_bytes(&identity, &keypair).to_vec();
        serialized.extend_from_slice(&[0xAA, 0xBB]);

        assert!(matches!(
            deserialize_keypair_bytes(&serialized),
            Err(DeviceIdentityError::InvalidFileFormat)
        ));
    }

    #[test]
    fn deserialize_keypair_bytes_rejects_unknown_format_version() {
        let (identity, keypair) = generate("phase1-device".to_owned()).expect("generate fixture");
        let mut serialized = serialize_keypair_bytes(&identity, &keypair).to_vec();
        *serialized.first_mut().expect("version byte") = 0xFF;

        assert!(matches!(
            deserialize_keypair_bytes(&serialized),
            Err(DeviceIdentityError::InvalidFileFormat)
        ));
    }

    #[test]
    fn serialize_then_deserialize_keypair_bytes_roundtrip_preserves_generated_keys() {
        let (identity, keypair) = generate("roundtrip-device".to_owned()).expect("generate");
        let serialized = serialize_keypair_bytes(&identity, &keypair);
        let (decoded_device_id, decoded_classical_public_key, decoded_keypair) =
            deserialize_keypair_bytes(serialized.as_slice()).expect("deserialize");
        let decoded_identity = DeviceIdentity {
            device_id: decoded_device_id,
            display_name: identity.display_name.clone(),
            classical_public_key: decoded_classical_public_key,
            pqc_public_key: identity.pqc_public_key.clone(),
            signing_public_key: identity.signing_public_key.clone(),
            created_at: identity.created_at,
            trust_state: identity.trust_state,
        };

        let reserialized = serialize_keypair_bytes(&decoded_identity, &decoded_keypair);
        assert_eq!(serialized.as_slice(), reserialized.as_slice());
    }

    #[test]
    fn serialize_identity_text_roundtrip_preserves_identity_fields() {
        let (identity, _keypair) =
            generate("identity-text-roundtrip".to_owned()).expect("generate");

        let serialized = serialize_identity_text(&identity);
        let parsed = deserialize_identity_text(&serialized).expect("identity text roundtrip");

        assert_eq!(parsed.device_id, identity.device_id);
        assert_eq!(parsed.display_name, identity.display_name);
        assert!(bool::from(
            parsed
                .classical_public_key
                .ct_eq(&identity.classical_public_key)
        ));
        assert!(bool::from(
            parsed.pqc_public_key.ct_eq(&identity.pqc_public_key)
        ));
        assert_eq!(parsed.created_at, identity.created_at);
        assert_eq!(parsed.trust_state, DeviceTrustState::Untrusted);
        assert_eq!(
            parsed
                .signing_public_key
                .as_ref()
                .expect("parsed signing key")
                .algorithm(),
            identity
                .signing_public_key
                .as_ref()
                .expect("source signing key")
                .algorithm()
        );
        assert_eq!(
            parsed
                .signing_public_key
                .as_ref()
                .expect("parsed signing key")
                .as_bytes(),
            identity
                .signing_public_key
                .as_ref()
                .expect("source signing key")
                .as_bytes()
        );
    }

    #[test]
    fn device_trust_state_from_u8_rejects_unknown_value() {
        assert!(matches!(
            device_trust_state_from_u8(7),
            Err(DeviceIdentityError::InvalidFileFormat)
        ));
    }

    #[test]
    fn sealed_device_key_file_roundtrip_preserves_identity_and_keypair() {
        let (mut identity, keypair) = generate("sealed-device".to_owned()).expect("generate");
        identity.trust_state = DeviceTrustState::Approved;
        let dkek = meissnerseal_crypto::types::AeadKey::from_bytes([0x5A; 32]);

        let sealed = SealedDeviceKeyFile::seal(&identity, &keypair, &dkek).expect("seal");
        let (opened_identity, opened_keypair) =
            SealedDeviceKeyFile::open(sealed.as_slice(), &dkek).expect("open");

        assert_eq!(opened_identity.device_id, identity.device_id);
        assert_eq!(opened_identity.display_name, identity.display_name);
        assert_eq!(opened_identity.created_at, identity.created_at);
        assert_eq!(opened_identity.trust_state, identity.trust_state);
        assert!(bool::from(
            opened_identity
                .classical_public_key
                .ct_eq(&identity.classical_public_key)
        ));
        assert_eq!(
            opened_identity
                .signing_public_key
                .as_ref()
                .expect("signing key")
                .as_bytes(),
            identity
                .signing_public_key
                .as_ref()
                .expect("signing key")
                .as_bytes()
        );
        let reopened_raw = serialize_keypair_bytes(&opened_identity, &opened_keypair);
        let original_raw = serialize_keypair_bytes(&identity, &keypair);
        assert_eq!(reopened_raw.as_slice(), original_raw.as_slice());
    }

    #[test]
    fn sealed_device_key_file_rejects_identity_mismatch_file() {
        let (identity_a, keypair_a) = generate("sealed-a".to_owned()).expect("generate a");
        let (mut identity_b, _keypair_b) = generate("sealed-b".to_owned()).expect("generate b");
        identity_b.classical_public_key = identity_a.classical_public_key.clone();
        let dkek = meissnerseal_crypto::types::AeadKey::from_bytes([0x6B; 32]);

        let mut sealed = SealedDeviceKeyFile::seal(&identity_a, &keypair_a, &dkek).expect("seal");
        let replacement_identity = serialize_identity_bytes(&identity_b).expect("identity bytes");
        replace_identity_payload_in_sealed_file(&mut sealed, replacement_identity.as_slice());

        assert!(matches!(
            SealedDeviceKeyFile::open(sealed.as_slice(), &dkek),
            Err(DeviceIdentityError::OpenFailed | DeviceIdentityError::IdentityFingerprintMismatch)
        ));
    }

    #[test]
    fn sealed_device_key_file_rejects_tamper() {
        let (identity, keypair) = generate("sealed-tamper".to_owned()).expect("generate");
        let dkek = meissnerseal_crypto::types::AeadKey::from_bytes([0x7C; 32]);

        let mut sealed = SealedDeviceKeyFile::seal(&identity, &keypair, &dkek).expect("seal");
        let last = sealed.last_mut().expect("ciphertext byte");
        *last ^= 0x01;

        assert!(matches!(
            SealedDeviceKeyFile::open(sealed.as_slice(), &dkek),
            Err(DeviceIdentityError::OpenFailed)
        ));
    }

    fn identity_with_state(
        trust_state: DeviceTrustState,
        signing_public_key: Option<SigningPublicKey>,
    ) -> DeviceIdentity {
        DeviceIdentity {
            device_id: [0x44; DEVICE_ID_LEN],
            display_name: "phase1-device".to_owned(),
            classical_public_key: Key::from_bytes([0x11; 32]),
            pqc_public_key: Key::from_bytes([0x22; 1184]),
            signing_public_key,
            created_at: 1_725_000_000_000,
            trust_state,
        }
    }

    #[allow(clippy::arithmetic_side_effects, clippy::indexing_slicing)]
    fn replace_identity_payload_in_sealed_file(sealed: &mut [u8], replacement: &[u8]) {
        let identity_len_offset = SEALED_DEVICE_KEY_FILE_MAGIC.len() + 1;
        let identity_len = u32::try_from(replacement.len()).expect("replacement len fits u32");
        sealed[identity_len_offset..identity_len_offset + 4]
            .copy_from_slice(&identity_len.to_le_bytes());
        let identity_offset = identity_len_offset + 4;
        let identity_end = identity_offset + replacement.len();
        sealed[identity_offset..identity_end].copy_from_slice(replacement);
    }

    #[test]
    fn phase4_fixture_verified_and_approved_states_are_sender_eligible() {
        let (verified_identity, _) = generate("verified-sender".to_owned()).expect("generate");
        let approved_identity = DeviceIdentity {
            trust_state: DeviceTrustState::Approved,
            ..verified_identity
        };
        approved_identity
            .validate()
            .expect("approved identity remains valid");

        assert!(matches!(
            approved_identity.trust_state,
            DeviceTrustState::Approved
        ));
        assert!(approved_identity.signing_public_key.is_some());
    }

    #[test]
    fn phase4_fixture_other_states_remain_sender_ineligible() {
        let signing_public_key = Some(SigningPublicKey::new(
            SigningAlgorithmId::Ed25519V1,
            vec![0x55; 32],
        ));
        let states = [
            DeviceTrustState::Untrusted,
            DeviceTrustState::PendingInbound,
            DeviceTrustState::PendingOutbound,
            DeviceTrustState::Revoked,
            DeviceTrustState::Expired,
        ];

        for state in states {
            let identity = identity_with_state(state, signing_public_key.clone());
            identity
                .validate()
                .expect("fixture identity remains structurally valid");
            assert!(!matches!(
                identity.trust_state,
                DeviceTrustState::Verified | DeviceTrustState::Approved
            ));
        }
    }

    #[test]
    fn trusted_sender_from_verified_accepts_verified_and_approved() {
        for state in [DeviceTrustState::Verified, DeviceTrustState::Approved] {
            let identity = identity_with_state(
                state,
                Some(SigningPublicKey::new(
                    SigningAlgorithmId::Ed25519V1,
                    vec![0x66; 32],
                )),
            );

            let trusted = TrustedSender::from_verified(&identity).expect("trusted sender");

            let _ = trusted;
        }
    }

    #[test]
    fn trusted_sender_from_verified_rejects_non_eligible_states() {
        let signing_public_key = Some(SigningPublicKey::new(
            SigningAlgorithmId::Ed25519V1,
            vec![0x77; 32],
        ));

        for state in [
            DeviceTrustState::Untrusted,
            DeviceTrustState::PendingInbound,
            DeviceTrustState::PendingOutbound,
            DeviceTrustState::Revoked,
            DeviceTrustState::Expired,
        ] {
            let identity = identity_with_state(state, signing_public_key.clone());

            assert!(matches!(
                TrustedSender::from_verified(&identity),
                Err(TransferError::UntrustedSender)
            ));
        }
    }

    #[test]
    fn trusted_sender_from_verified_rejects_missing_signing_key() {
        let identity = identity_with_state(DeviceTrustState::Verified, None);

        assert!(matches!(
            TrustedSender::from_verified(&identity),
            Err(TransferError::UntrustedSender)
        ));
    }
}
