// SPDX-License-Identifier: Apache-2.0
//! Device identity and enrollment key material.

use meissnerseal_pqc::{
    hybrid::{X25519PrivateKey, X25519PublicKey},
    mldsa::{self, SigningAlgorithmId, SigningPrivateKey, SigningPublicKey},
    mlkem::{MlKemPrivateKey, MlKemPublicKey},
};
use zeroize::{Zeroize, ZeroizeOnDrop};

/// Device identifier length in bytes.
pub const DEVICE_ID_LEN: usize = 16;

/// Domain-separation prefix for DEVICE-1 enrollment signatures (F-39).
pub const DEVICE_ENROLLMENT_SIGNING_DOMAIN: &[u8] = b"meissnerseal.device.enrollment.v1\x00";

/// A 128-bit random device identifier.
pub type DeviceId = [u8; DEVICE_ID_LEN];

/// Unix timestamp in milliseconds.
pub type Timestamp = u64;

/// Device trust state for pairing, sync, and transfer policy.
///
/// # Contract
///
/// ## Preconditions
/// - Callers must validate state transitions before persisting or acting on
///   trust changes.
/// - `Verified` and `Approved` identities must carry a signing public key.
///
/// ## Postconditions
/// - Validation rejects `Verified` or `Approved` identities that have no
///   signing public key.
///
/// ## Invariants
/// - `Revoked` and `Expired` are terminal states for DEVICE-1 policy.
/// - Invalid transitions return `Err`; they are never silently accepted.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DeviceTrustState {
    Untrusted,
    PendingInbound,
    PendingOutbound,
    Verified,
    Approved,
    Revoked,
    Expired,
}

/// Public device identity advertised in pairing and transfer metadata.
///
/// # Contract
///
/// ## Preconditions
/// - `device_id` must be 128-bit random material generated by the core device
///   identity generator.
/// - `classical_public_key` must be the public half of an X25519 keypair from
///   `meissnerseal-pqc`.
/// - `pqc_public_key` must be the public half of an ML-KEM-768 keypair from
///   `meissnerseal-pqc`.
/// - `signing_public_key`, when present, must be algorithm-tagged per ADR-028.
///
/// ## Postconditions
/// - `validate()` returns `Err` for identities whose trust state requires a
///   signing key but whose `signing_public_key` is `None`.
///
/// ## Invariants
/// - The signing key type is `mldsa::SigningPublicKey`; the obsolete bare
///   Ed25519 type in `transfer_profile_v1.md §6` is superseded by ADR-028.
/// - Public key bytes never travel without their algorithm identifier.
#[derive(Debug)]
pub struct DeviceIdentity {
    pub device_id: DeviceId,
    pub display_name: String,
    pub classical_public_key: X25519PublicKey,
    pub pqc_public_key: MlKemPublicKey,
    pub signing_public_key: Option<SigningPublicKey>,
    pub created_at: Timestamp,
    pub trust_state: DeviceTrustState,
}

impl DeviceIdentity {
    /// Validate the structural invariants of a device identity.
    ///
    /// # Contract
    ///
    /// ## Preconditions
    /// - Identity fields must be fully populated before reaching sync or
    ///   transfer logic.
    ///
    /// ## Postconditions
    /// - Returns `Err(MissingSigningKey)` for `Verified` or `Approved`
    ///   identities without a signing public key.
    /// - Returns `Err(EmptyDisplayName)` when `display_name` is empty.
    ///
    /// ## Invariants
    /// - Validation is fail-closed and returns no partial trust decision.
    pub fn validate(&self) -> Result<()> {
        if self.display_name.is_empty() {
            return Err(DeviceIdentityError::EmptyDisplayName);
        }
        if matches!(
            self.trust_state,
            DeviceTrustState::Verified | DeviceTrustState::Approved
        ) && self.signing_public_key.is_none()
        {
            return Err(DeviceIdentityError::MissingSigningKey);
        }
        Ok(())
    }
}

/// Private key holder for a device identity.
///
/// # Contract
///
/// ## Preconditions
/// - Constructed only by `generate()` after all required keypairs have been
///   generated successfully.
/// - No partial `DeviceKeypair` is returned if any key generation step fails.
///
/// ## Postconditions
/// - Contains the X25519 private key, ML-KEM-768 private key, and Ed25519V1
///   signing private key matching a generated `DeviceIdentity`.
///
/// ## Invariants
/// - Implements `Zeroize` and `ZeroizeOnDrop`.
/// - `Debug` output is redacted and never includes key material.
/// - Does not implement `Clone`.
pub struct DeviceKeypair {
    classical_private_key: X25519PrivateKey,
    pqc_private_key: MlKemPrivateKey,
    signing_private_key: SigningPrivateKey,
}

impl DeviceKeypair {
    #[must_use]
    pub(crate) fn new(
        classical_private_key: X25519PrivateKey,
        pqc_private_key: MlKemPrivateKey,
        signing_private_key: SigningPrivateKey,
    ) -> Self {
        Self {
            classical_private_key,
            pqc_private_key,
            signing_private_key,
        }
    }
}

impl core::fmt::Debug for DeviceKeypair {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str("DeviceKeypair([REDACTED])")
    }
}

impl Zeroize for DeviceKeypair {
    fn zeroize(&mut self) {
        self.classical_private_key.zeroize();
        self.pqc_private_key.zeroize();
        self.signing_private_key.zeroize();
    }
}

impl ZeroizeOnDrop for DeviceKeypair {}

#[derive(Debug, thiserror::Error)]
pub enum DeviceIdentityError {
    #[error("device identity generation is not implemented")]
    Unimplemented,
    #[error("device display name must not be empty")]
    EmptyDisplayName,
    #[error("device identity requires a signing public key")]
    MissingSigningKey,
    #[error("invalid signing public key length")]
    InvalidSigningPublicKeyLength,
    #[error("device random bytes length mismatch")]
    RandomBytesLength,
    #[error("device key generation failed")]
    KeyGenerationFailed,
    #[error("device timestamp overflow")]
    TimestampOverflow,
    #[error("device signing operation failed")]
    SigningFailed,
}

pub type Result<T> = core::result::Result<T, DeviceIdentityError>;

/// Generate a new public device identity and private key holder.
///
/// # Contract
///
/// ## Preconditions
/// - `display_name` must be non-empty.
/// - All cryptographic key generation must go through `meissnerseal-pqc`
///   abstractions; core must not call `ed25519-dalek`, `x25519-dalek`, or
///   ML-KEM backends directly.
///
/// ## Postconditions
/// - On success, returns a 16-byte random `device_id`, X25519 public key,
///   ML-KEM-768 public key, Ed25519V1 signing public key, creation timestamp,
///   and matching private `DeviceKeypair`.
/// - On any failure, returns `Err` and exposes no partial key material.
///
/// ## Invariants
/// - Generated signing material is tagged `SigningAlgorithmId::Ed25519V1`.
/// - No plaintext secret key material is logged, printed, or included in
///   errors.
pub fn generate(display_name: String) -> Result<(DeviceIdentity, DeviceKeypair)> {
    if display_name.is_empty() {
        return Err(DeviceIdentityError::EmptyDisplayName);
    }
    let id_bytes = meissnerseal_crypto::rng::random_bytes(DEVICE_ID_LEN);
    let device_id: DeviceId = id_bytes
        .try_into()
        .map_err(|_| DeviceIdentityError::RandomBytesLength)?;
    let (classical_private, classical_public) = meissnerseal_pqc::hybrid::x25519_keypair();
    let (pqc_public, pqc_private) =
        meissnerseal_pqc::mlkem::keypair().map_err(|_| DeviceIdentityError::KeyGenerationFailed)?;
    let (signing_public, signing_private) = meissnerseal_pqc::mldsa::ed25519_keypair();
    let created_at = unix_time_millis()?;

    let identity = DeviceIdentity {
        device_id,
        display_name,
        classical_public_key: classical_public,
        pqc_public_key: pqc_public,
        signing_public_key: Some(signing_public),
        created_at,
        trust_state: DeviceTrustState::Untrusted,
    };
    let keypair = DeviceKeypair::new(classical_private, pqc_private, signing_private);
    Ok((identity, keypair))
}

/// Construct a validated Ed25519V1 signing public key from fixed-length bytes.
///
/// # Contract
///
/// ## Preconditions
/// - `bytes` must be exactly the 32-byte Ed25519 public key encoding.
///
/// ## Postconditions
/// - Returns a `SigningPublicKey` tagged `SigningAlgorithmId::Ed25519V1`.
///
/// ## Invariants
/// - Callers cannot accidentally construct a wrong-length Ed25519 key through
///   this typed constructor.
pub fn try_new_ed25519_signing_public_key(bytes: [u8; 32]) -> Result<SigningPublicKey> {
    Ok(SigningPublicKey::new(
        SigningAlgorithmId::Ed25519V1,
        bytes.to_vec(),
    ))
}

/// Construct a validated signing public key from byte slices.
///
/// # Contract
///
/// ## Preconditions
/// - `algorithm` determines the exact expected byte length.
///
/// ## Postconditions
/// - Ed25519V1 accepts exactly 32 bytes and rejects all other lengths.
/// - The hybrid slot fails closed until the future PQ signing backend is
///   implemented.
///
/// ## Invariants
/// - This helper closes F-40 for callers that receive wire bytes before they
///   can be promoted into fixed-length arrays.
pub fn try_new_signing_public_key(
    algorithm: SigningAlgorithmId,
    bytes: &[u8],
) -> Result<SigningPublicKey> {
    match algorithm {
        SigningAlgorithmId::Ed25519V1 => {
            let key_bytes: [u8; 32] = bytes
                .try_into()
                .map_err(|_| DeviceIdentityError::InvalidSigningPublicKeyLength)?;
            try_new_ed25519_signing_public_key(key_bytes)
        }
        SigningAlgorithmId::Ed25519MlDsa87HybridV1 => Err(DeviceIdentityError::Unimplemented),
    }
}

/// Build the domain-separated enrollment transcript bytes for signing.
///
/// # Contract
///
/// ## Preconditions
/// - `message` is the device-enrollment payload to authenticate.
///
/// ## Postconditions
/// - Returns `DEVICE_ENROLLMENT_SIGNING_DOMAIN || message`.
///
/// ## Invariants
/// - All bytes passed from DEVICE-1 to `mldsa::sign()` must be produced by
///   this helper or by an equivalent construction with the same prefix.
pub fn enrollment_signing_message(message: &[u8]) -> Vec<u8> {
    let mut signed = Vec::new();
    signed.extend_from_slice(DEVICE_ENROLLMENT_SIGNING_DOMAIN);
    signed.extend_from_slice(message);
    signed
}

/// Sign a device-enrollment payload with the DEVICE-1 domain prefix.
///
/// # Contract
///
/// ## Preconditions
/// - `private_key` must be an algorithm-tagged signing key from the generated
///   device keypair.
/// - `message` must be the raw device-enrollment payload, not already signed
///   content.
///
/// ## Postconditions
/// - Calls `mldsa::sign()` with
///   `b"meissnerseal.device.enrollment.v1\x00" || message`.
/// - Returns `Err` if the PQC signing boundary rejects the operation.
///
/// ## Invariants
/// - Core owns the F-39 domain-separation prefix; `meissnerseal-pqc` does not
///   add it implicitly.
pub fn sign_enrollment_message(
    private_key: &SigningPrivateKey,
    message: &[u8],
) -> Result<mldsa::Signature> {
    let prefixed = enrollment_signing_message(message);
    mldsa::sign(private_key, &prefixed).map_err(|_| DeviceIdentityError::SigningFailed)
}

fn unix_time_millis() -> Result<Timestamp> {
    let millis = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis();
    Timestamp::try_from(millis).map_err(|_| DeviceIdentityError::TimestampOverflow)
}

#[cfg(test)]
#[allow(clippy::expect_used)]
mod tests {
    use super::*;
    use meissnerseal_crypto::types::Key;
    use static_assertions::assert_not_impl_any;

    assert_not_impl_any!(DeviceKeypair: Clone);

    const TEST_MESSAGE: &[u8] = b"device enrollment payload";

    #[test]
    fn generate_returns_device_identity_with_128_bit_device_id() {
        let (identity, _keypair) =
            generate("phase1-device".to_owned()).expect("Phase 2 generate succeeds");

        assert_eq!(identity.device_id.len(), DEVICE_ID_LEN);
    }

    #[test]
    fn generate_produces_ed25519_v1_signing_public_key() {
        let (identity, _keypair) =
            generate("phase1-device".to_owned()).expect("Phase 2 generate succeeds");
        let signing_public_key = identity
            .signing_public_key
            .as_ref()
            .expect("generated identity has signing key");

        assert_eq!(
            signing_public_key.algorithm(),
            SigningAlgorithmId::Ed25519V1
        );
    }

    #[test]
    fn enrollment_signing_message_prepends_domain_prefix() {
        let signed = enrollment_signing_message(TEST_MESSAGE);

        assert!(signed.starts_with(DEVICE_ENROLLMENT_SIGNING_DOMAIN));
        assert!(signed.ends_with(TEST_MESSAGE));
        assert_ne!(signed.as_slice(), TEST_MESSAGE);
    }

    #[test]
    fn prefixed_and_unprefixed_messages_produce_different_signatures() {
        let private_key = SigningPrivateKey::new(SigningAlgorithmId::Ed25519V1, vec![0x11; 32]);
        let raw_signature = mldsa::sign(&private_key, TEST_MESSAGE).expect("raw sign succeeds");
        let signed_message = enrollment_signing_message(TEST_MESSAGE);
        let prefixed_signature =
            mldsa::sign(&private_key, &signed_message).expect("prefixed sign succeeds");

        assert_ne!(raw_signature.as_bytes(), prefixed_signature.as_bytes());
    }

    #[test]
    fn try_new_ed25519_signing_public_key_rejects_wrong_length_input() {
        let wrong_length = [0u8; 31];

        assert!(matches!(
            try_new_signing_public_key(SigningAlgorithmId::Ed25519V1, &wrong_length),
            Err(DeviceIdentityError::InvalidSigningPublicKeyLength)
        ));
    }

    #[test]
    fn verified_or_approved_identity_without_signing_key_fails_validation() {
        let verified = identity_with_state(DeviceTrustState::Verified, None);
        let approved = identity_with_state(DeviceTrustState::Approved, None);

        assert!(matches!(
            verified.validate(),
            Err(DeviceIdentityError::MissingSigningKey)
        ));
        assert!(matches!(
            approved.validate(),
            Err(DeviceIdentityError::MissingSigningKey)
        ));
    }

    #[test]
    fn device_keypair_debug_is_redacted() {
        let keypair = DeviceKeypair::new(
            Key::from_bytes([0xA1; 32]),
            Key::from_bytes([0xB2; 2400]),
            SigningPrivateKey::new(SigningAlgorithmId::Ed25519V1, vec![0xC3; 32]),
        );
        let debug = format!("{keypair:?}");

        assert_eq!(debug, "DeviceKeypair([REDACTED])");
        assert!(!debug.contains("A1"));
        assert!(!debug.contains("B2"));
        assert!(!debug.contains("C3"));
    }

    #[test]
    fn generate_with_empty_display_name_returns_err() {
        assert!(matches!(
            generate(String::new()),
            Err(DeviceIdentityError::EmptyDisplayName)
        ));
    }

    fn identity_with_state(
        trust_state: DeviceTrustState,
        signing_public_key: Option<SigningPublicKey>,
    ) -> DeviceIdentity {
        DeviceIdentity {
            device_id: [0x44; DEVICE_ID_LEN],
            display_name: "phase1-device".to_owned(),
            classical_public_key: Key::from_bytes([0x11; 32]),
            pqc_public_key: Key::from_bytes([0x22; 1184]),
            signing_public_key,
            created_at: 1_725_000_000_000,
            trust_state,
        }
    }
}
