// SPDX-License-Identifier: Apache-2.0
//! DEVICE-2 out-of-band pairing payload and session contracts.

use crate::keys::device::{DeviceId, DeviceIdentity, DeviceTrustState};

/// DEVICE-2 pairing payload protocol version.
pub const PAIRING_PROTOCOL_VERSION_V1: u16 = 0x0001;

/// SHA-256 public key fingerprint length.
pub const PAIRING_FINGERPRINT_LEN: usize = 32;

/// Random pairing nonce length in bytes.
pub const PAIRING_NONCE_LEN: usize = 32;

/// Short authentication string length in lowercase hex characters.
pub const PAIRING_SAS_HEX_LEN: usize = 6;

/// SHA-256 public key fingerprint.
pub type PublicKeyFingerprint = [u8; PAIRING_FINGERPRINT_LEN];

/// Random 256-bit pairing nonce.
pub type PairingNonce = [u8; PAIRING_NONCE_LEN];

/// Six-character out-of-band short authentication string.
pub type ShortAuthenticationString = String;

/// QR/manual pairing payload exchanged over an out-of-band channel.
///
/// # Contract
///
/// ## Preconditions
/// - `protocol_version` must be `PAIRING_PROTOCOL_VERSION_V1`.
/// - `device_id` must be the 128-bit device identifier from `DeviceIdentity`.
/// - Fingerprints must be full 32-byte SHA-256 digests of the raw public key
///   bytes named by `transfer_profile_v1.md §6`.
/// - `pairing_nonce` must be a random 256-bit nonzero value.
///
/// ## Postconditions
/// - `validate_pairing_payload()` rejects unknown versions and all-zero
///   nonces.
///
/// ## Invariants
/// - Contains only public metadata, public key fingerprints, capabilities, and
///   a non-secret nonce; deriving `Debug` is allowed.
/// - Does not contain raw public keys or private key material.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PairingPayload {
    pub protocol_version: u16,
    pub device_id: DeviceId,
    pub display_name: String,
    pub classical_public_key_fingerprint: PublicKeyFingerprint,
    pub pqc_public_key_fingerprint: PublicKeyFingerprint,
    pub signing_public_key_fingerprint: PublicKeyFingerprint,
    pub capabilities: u32,
    pub pairing_nonce: PairingNonce,
}

/// Pairing transcript authenticated by DEVICE-1 enrollment signing.
///
/// # Contract
///
/// ## Preconditions
/// - `payload` must pass `validate_pairing_payload()`.
/// - `transcript_hash` must be SHA-256 over the canonical pairing transcript.
///
/// ## Postconditions
/// - Phase 2 must sign the transcript using `sign_enrollment_message()` and
///   the existing DEVICE-1 enrollment domain prefix.
///
/// ## Invariants
/// - No separate pairing signing domain is introduced in Phase 1.
/// - The transcript binds the full payload, including capabilities and nonce.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PairingTranscript {
    pub payload: PairingPayload,
    pub transcript_hash: [u8; 32],
}

/// Local pairing state for an out-of-band QR/manual exchange.
///
/// # Contract
///
/// ## Preconditions
/// - Sessions are created only from validated local and remote pairing data.
/// - The OOB channel is user-mediated; this type does not represent network
///   transport state.
///
/// ## Postconditions
/// - Phase 2 must transition trust state only through
///   `validate_trust_transition()`.
///
/// ## Invariants
/// - Holds no `DeviceKeypair`, signing private key, plaintext secret, or
///   transport handle.
/// - `Debug` output contains only public identifiers and non-secret SAS text.
#[derive(Debug, Eq, PartialEq)]
pub struct PairingSession {
    pub local_device_id: DeviceId,
    pub remote_device_id: DeviceId,
    pub sas: ShortAuthenticationString,
    pub state: DeviceTrustState,
}

/// DEVICE-2 pairing errors.
#[derive(Debug, thiserror::Error, Eq, PartialEq)]
pub enum PairingError {
    #[error("pairing implementation unavailable")]
    Unimplemented,
    #[error("pairing payload uses an unknown protocol version")]
    UnknownProtocolVersion,
    #[error("pairing identity requires a signing public key")]
    MissingSigningPublicKey,
    #[error("device display name must not be empty")]
    EmptyDisplayName,
    #[error("pairing nonce must be nonzero")]
    ZeroPairingNonce,
    #[error("pairing nonce generation failed")]
    NonceGenerationFailed,
    #[error("invalid device trust state transition")]
    InvalidTrustTransition,
}

pub type Result<T> = core::result::Result<T, PairingError>;

/// Build a QR/manual out-of-band pairing payload from a device identity.
///
/// # Contract
///
/// ## Preconditions
/// - `identity.signing_public_key` must be `Some`; identities without signing
///   keys cannot be paired or approved.
/// - `identity` public key fields must be the public keys generated by
///   DEVICE-1.
/// - `capabilities` is the v1 u32 capability bitmask.
///
/// ## Postconditions
/// - On success, returns a payload with protocol version v1, full 32-byte
///   SHA-256 public key fingerprints, the provided capabilities bitmask, and a
///   fresh nonzero 256-bit pairing nonce.
/// - On failure, returns `Err` without producing a partial payload.
///
/// ## Invariants
/// - Hashing must use `meissnerseal_crypto::hash::sha256_bytes`.
/// - Nonce generation must use `meissnerseal_crypto::rng::random_bytes`.
/// - Core must not call PQC or primitive crypto backends directly.
pub fn build_pairing_payload(
    identity: &DeviceIdentity,
    capabilities: u32,
) -> Result<PairingPayload> {
    let signing_public_key = identity
        .signing_public_key
        .as_ref()
        .ok_or(PairingError::MissingSigningPublicKey)?;
    if identity.display_name.is_empty() {
        return Err(PairingError::EmptyDisplayName);
    }

    let pairing_nonce = generate_pairing_nonce()?;
    let classical_public_key_fingerprint =
        meissnerseal_crypto::hash::sha256_bytes(identity.classical_public_key.as_slice());
    let pqc_public_key_fingerprint =
        meissnerseal_crypto::hash::sha256_bytes(identity.pqc_public_key.as_slice());
    let signing_public_key_fingerprint =
        meissnerseal_crypto::hash::sha256_bytes(signing_public_key.as_bytes());

    Ok(PairingPayload {
        protocol_version: PAIRING_PROTOCOL_VERSION_V1,
        device_id: identity.device_id,
        display_name: identity.display_name.clone(),
        classical_public_key_fingerprint,
        pqc_public_key_fingerprint,
        signing_public_key_fingerprint,
        capabilities,
        pairing_nonce,
    })
}

/// Validate a received QR/manual out-of-band pairing payload.
///
/// # Contract
///
/// ## Preconditions
/// - `payload` is untrusted data received through a QR/manual OOB channel.
///
/// ## Postconditions
/// - Returns `Err(UnknownProtocolVersion)` for every version other than v1.
/// - Returns `Err(ZeroPairingNonce)` when `pairing_nonce` is all zeros.
/// - Returns `Ok(())` only after all structural checks pass.
///
/// ## Invariants
/// - Validation fails closed and returns no partial trust decision.
/// - This function performs no key derivation and no network access.
pub fn validate_pairing_payload(payload: &PairingPayload) -> Result<()> {
    if payload.protocol_version != PAIRING_PROTOCOL_VERSION_V1 {
        return Err(PairingError::UnknownProtocolVersion);
    }
    if payload.pairing_nonce.iter().all(|byte| *byte == 0) {
        return Err(PairingError::ZeroPairingNonce);
    }
    if payload.display_name.is_empty() {
        return Err(PairingError::EmptyDisplayName);
    }

    Ok(())
}

/// Compute the DEVICE-2 pairing transcript hash.
///
/// # Contract
///
/// ## Preconditions
/// - `payload` must be structurally valid per `validate_pairing_payload()`.
///
/// ## Postconditions
/// - Returns the SHA-256 hash of the canonical v1 pairing transcript bytes.
/// - Returns `Err` if the payload is invalid.
///
/// ## Invariants
/// - Hashing must use `meissnerseal_crypto::hash::sha256_bytes`.
/// - The transcript must bind protocol version, device ID, display name,
///   all public key fingerprints, capabilities, and pairing nonce.
pub fn compute_pairing_transcript(payload: &PairingPayload) -> Result<PairingTranscript> {
    validate_pairing_payload(payload)?;

    let display_name_len =
        u32::try_from(payload.display_name.len()).map_err(|_| PairingError::EmptyDisplayName)?;
    let mut transcript = Vec::new();
    transcript.extend_from_slice(&payload.protocol_version.to_le_bytes());
    transcript.extend_from_slice(&payload.device_id);
    transcript.extend_from_slice(&display_name_len.to_le_bytes());
    transcript.extend_from_slice(payload.display_name.as_bytes());
    transcript.extend_from_slice(&payload.classical_public_key_fingerprint);
    transcript.extend_from_slice(&payload.pqc_public_key_fingerprint);
    transcript.extend_from_slice(&payload.signing_public_key_fingerprint);
    transcript.extend_from_slice(&payload.capabilities.to_le_bytes());
    transcript.extend_from_slice(&payload.pairing_nonce);

    Ok(PairingTranscript {
        payload: payload.clone(),
        transcript_hash: meissnerseal_crypto::hash::sha256_bytes(&transcript),
    })
}

/// Derive the six-hex-character short authentication string.
///
/// # Contract
///
/// ## Preconditions
/// - `pairing_nonce` must be the 32-byte nonce from the validated pairing
///   payload.
/// - `transcript_hash` must be the SHA-256 transcript hash for the same
///   pairing payload.
///
/// ## Postconditions
/// - Returns lowercase hex encoding of
///   `SHA256(pairing_nonce || transcript_hash)[0..3]`.
///
/// ## Invariants
/// - Hashing must use `meissnerseal_crypto::hash::sha256_bytes`.
/// - The SAS is display-only OOB verification data, not a secret.
pub fn derive_short_authentication_string(
    pairing_nonce: &PairingNonce,
    transcript_hash: &[u8; 32],
) -> Result<ShortAuthenticationString> {
    let mut input = Vec::new();
    input.extend_from_slice(pairing_nonce);
    input.extend_from_slice(transcript_hash);
    let digest = meissnerseal_crypto::hash::sha256_bytes(&input);
    let [first, second, third, ..] = digest;

    Ok(format!("{first:02x}{second:02x}{third:02x}"))
}

/// Validate a DEVICE-2 trust-state transition.
///
/// # Contract
///
/// ## Preconditions
/// - `from` is the currently persisted trust state.
/// - `to` is the requested next trust state for the same device.
///
/// ## Postconditions
/// - Allows `Untrusted -> PendingInbound`.
/// - Allows `Untrusted -> PendingOutbound`.
/// - Allows pending states to move to `Verified`.
/// - Allows `Verified -> Approved`.
/// - Returns `Err(InvalidTrustTransition)` for skipped or backward states.
///
/// ## Invariants
/// - Invalid transitions are never silently accepted.
/// - `Revoked` and `Expired` remain terminal states.
pub fn validate_trust_transition(from: DeviceTrustState, to: DeviceTrustState) -> Result<()> {
    match (from, to) {
        (DeviceTrustState::Untrusted, DeviceTrustState::PendingInbound)
        | (DeviceTrustState::Untrusted, DeviceTrustState::PendingOutbound)
        | (DeviceTrustState::PendingInbound, DeviceTrustState::Verified)
        | (DeviceTrustState::PendingOutbound, DeviceTrustState::Verified)
        | (DeviceTrustState::Verified, DeviceTrustState::Approved)
        | (DeviceTrustState::Untrusted, DeviceTrustState::Revoked)
        | (DeviceTrustState::PendingInbound, DeviceTrustState::Revoked)
        | (DeviceTrustState::PendingOutbound, DeviceTrustState::Revoked)
        | (DeviceTrustState::Verified, DeviceTrustState::Revoked)
        | (DeviceTrustState::Approved, DeviceTrustState::Revoked)
        | (DeviceTrustState::Revoked, DeviceTrustState::Revoked)
        | (DeviceTrustState::Expired, DeviceTrustState::Revoked)
        | (DeviceTrustState::Untrusted, DeviceTrustState::Expired)
        | (DeviceTrustState::PendingInbound, DeviceTrustState::Expired)
        | (DeviceTrustState::PendingOutbound, DeviceTrustState::Expired)
        | (DeviceTrustState::Verified, DeviceTrustState::Expired)
        | (DeviceTrustState::Approved, DeviceTrustState::Expired)
        | (DeviceTrustState::Revoked, DeviceTrustState::Expired)
        | (DeviceTrustState::Expired, DeviceTrustState::Expired) => Ok(()),
        _ => Err(PairingError::InvalidTrustTransition),
    }
}

fn generate_pairing_nonce() -> Result<PairingNonce> {
    let first = random_nonce_candidate()?;
    if first.iter().any(|byte| *byte != 0) {
        return Ok(first);
    }

    let second = random_nonce_candidate()?;
    if second.iter().any(|byte| *byte != 0) {
        return Ok(second);
    }

    Err(PairingError::NonceGenerationFailed)
}

fn random_nonce_candidate() -> Result<PairingNonce> {
    meissnerseal_crypto::rng::random_bytes(PAIRING_NONCE_LEN)
        .try_into()
        .map_err(|_| PairingError::NonceGenerationFailed)
}

#[cfg(test)]
#[allow(clippy::expect_used)]
mod tests {
    use super::*;
    use meissnerseal_crypto::types::Key;
    use meissnerseal_pqc::mldsa::{SigningAlgorithmId, SigningPublicKey};
    use proptest::prelude::*;

    proptest! {
        #[test]
        fn distinct_device_identities_produce_distinct_pairing_payloads(
            first_device_id in proptest::array::uniform16(0u8..),
            second_device_id in proptest::array::uniform16(0u8..),
            first_classical in proptest::array::uniform32(0u8..),
            second_classical in proptest::array::uniform32(0u8..),
            first_pqc in proptest::array::uniform::<_, 1184>(0u8..),
            second_pqc in proptest::array::uniform::<_, 1184>(0u8..),
            first_signing in proptest::array::uniform32(0u8..),
            second_signing in proptest::array::uniform32(0u8..),
        ) {
            let first = identity(
                first_device_id,
                "first",
                first_classical,
                first_pqc,
                Some(first_signing),
                DeviceTrustState::Untrusted,
            );
            let second = identity(
                second_device_id,
                "second",
                second_classical,
                second_pqc,
                Some(second_signing),
                DeviceTrustState::Untrusted,
            );
            prop_assume!(identities_differ(&first, &second));

            let first_payload = build_pairing_payload(&first, 0x01).expect("payload");
            let second_payload = build_pairing_payload(&second, 0x01).expect("payload");

            prop_assert_ne!(first_payload, second_payload);
        }
    }

    #[test]
    fn build_pairing_payload_without_signing_key_returns_err() {
        let identity = identity(
            [0x11; 16],
            "missing-signing",
            [0x22; 32],
            [0x33; 1184],
            None,
            DeviceTrustState::Untrusted,
        );

        assert_eq!(
            build_pairing_payload(&identity, 0x01),
            Err(PairingError::MissingSigningPublicKey)
        );
    }

    #[test]
    fn build_pairing_payload_with_empty_display_name_returns_err() {
        let identity = identity(
            [0x11; 16],
            "",
            [0x22; 32],
            [0x33; 1184],
            Some([0x44; 32]),
            DeviceTrustState::Untrusted,
        );

        assert_eq!(
            build_pairing_payload(&identity, 0x01),
            Err(PairingError::EmptyDisplayName)
        );
    }

    #[test]
    fn validate_pairing_payload_rejects_unknown_protocol_version() {
        let mut payload = payload_fixture();
        payload.protocol_version = 0xffff;

        assert_eq!(
            validate_pairing_payload(&payload),
            Err(PairingError::UnknownProtocolVersion)
        );
    }

    #[test]
    fn validate_pairing_payload_rejects_zero_pairing_nonce() {
        let mut payload = payload_fixture();
        payload.pairing_nonce = [0u8; PAIRING_NONCE_LEN];

        assert_eq!(
            validate_pairing_payload(&payload),
            Err(PairingError::ZeroPairingNonce)
        );
    }

    #[test]
    fn sas_differs_for_two_different_pairing_nonces() {
        let transcript_hash = [0x44; 32];
        let first = [0x01; PAIRING_NONCE_LEN];
        let second = [0x02; PAIRING_NONCE_LEN];

        let first_sas =
            derive_short_authentication_string(&first, &transcript_hash).expect("first sas");
        let second_sas =
            derive_short_authentication_string(&second, &transcript_hash).expect("second sas");

        assert_eq!(first_sas.len(), PAIRING_SAS_HEX_LEN);
        assert_eq!(second_sas.len(), PAIRING_SAS_HEX_LEN);
        assert_ne!(first_sas, second_sas);
    }

    #[test]
    fn untrusted_to_pending_inbound_is_valid() {
        assert_eq!(
            validate_trust_transition(
                DeviceTrustState::Untrusted,
                DeviceTrustState::PendingInbound
            ),
            Ok(())
        );
    }

    #[test]
    fn verified_to_untrusted_is_invalid() {
        assert_eq!(
            validate_trust_transition(DeviceTrustState::Verified, DeviceTrustState::Untrusted),
            Err(PairingError::InvalidTrustTransition)
        );
    }

    #[test]
    fn pending_inbound_to_approved_skips_verified_and_is_invalid() {
        assert_eq!(
            validate_trust_transition(DeviceTrustState::PendingInbound, DeviceTrustState::Approved),
            Err(PairingError::InvalidTrustTransition)
        );
    }

    #[test]
    fn any_state_to_revoked_is_valid() {
        for from in [
            DeviceTrustState::Untrusted,
            DeviceTrustState::Verified,
            DeviceTrustState::Approved,
        ] {
            assert_eq!(
                validate_trust_transition(from, DeviceTrustState::Revoked),
                Ok(())
            );
        }
    }

    fn payload_fixture() -> PairingPayload {
        PairingPayload {
            protocol_version: PAIRING_PROTOCOL_VERSION_V1,
            device_id: [0x11; 16],
            display_name: "phase1-device".to_owned(),
            classical_public_key_fingerprint: [0x22; PAIRING_FINGERPRINT_LEN],
            pqc_public_key_fingerprint: [0x33; PAIRING_FINGERPRINT_LEN],
            signing_public_key_fingerprint: [0x44; PAIRING_FINGERPRINT_LEN],
            capabilities: 0x01,
            pairing_nonce: [0x55; PAIRING_NONCE_LEN],
        }
    }

    fn identity(
        device_id: DeviceId,
        display_name: &str,
        classical_public_key: [u8; 32],
        pqc_public_key: [u8; 1184],
        signing_public_key: Option<[u8; 32]>,
        trust_state: DeviceTrustState,
    ) -> DeviceIdentity {
        DeviceIdentity {
            device_id,
            display_name: display_name.to_owned(),
            classical_public_key: Key::from_bytes(classical_public_key),
            pqc_public_key: Key::from_bytes(pqc_public_key),
            signing_public_key: signing_public_key
                .map(|bytes| SigningPublicKey::new(SigningAlgorithmId::Ed25519V1, bytes.to_vec())),
            created_at: 1,
            trust_state,
        }
    }

    fn identities_differ(first: &DeviceIdentity, second: &DeviceIdentity) -> bool {
        first.device_id != second.device_id
            || first.display_name != second.display_name
            || first.classical_public_key.as_slice() != second.classical_public_key.as_slice()
            || first.pqc_public_key.as_slice() != second.pqc_public_key.as_slice()
            || first
                .signing_public_key
                .as_ref()
                .map(SigningPublicKey::as_bytes)
                != second
                    .signing_public_key
                    .as_ref()
                    .map(SigningPublicKey::as_bytes)
    }
}
